version: '3.4'

services:
  instancemanager:
    image: instancemanager
    volumes:
      - ~/.aws/credentials:~/.aws/credentials:ro
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ['node', '--inspect=0.0.0.0:9229', 'src/main']
