version: '3.4'

services:
  instancemanager:
    image: instancemanager
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ~/.aws:/root/.aws:ro
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
